image: Visual Studio 2017

platform: ARM

configuration: Release

before_build:
  - nuget restore TelegramWP10.sln

build:
  project: TelegramWP10.sln
  verbosity: minimal

after_build:
  - ps: Get-ChildItem -Recurse -Filter "*.appx" | % { Push-AppveyorArtifact $_.FullName }
